FROM aeons/elixir-gcc:1.4.1

ENV MIX_ENV=prod

WORKDIR /opt/app

# Install deps
RUN mkdir -p ./config
COPY mix.exs mix.lock ./
COPY config/* ./config/

RUN mkdir -p ./apps/memory/config
COPY ./apps/memory/mix.exs ./apps/memory/
COPY ./apps/memory/config/* ./apps/memory/config/

RUN mix do deps.get, deps.compile

# Add app code
COPY . .

# vim: set ft=dockerfile:
