FROM aeons/elixir-gcc:1.4.1

ENV MIX_ENV=prod

WORKDIR /opt/app

# Install deps
RUN mkdir -p ./config
COPY mix.exs mix.lock ./
COPY config/* ./config/

# Core app
RUN mkdir -p ./apps/core/config
COPY ./apps/core/mix.exs ./apps/core/

# Web app
RUN mkdir -p ./apps/web/config
COPY ./apps/web/mix.exs ./apps/web/
COPY ./apps/web/config/* ./apps/web/config/

# Memory app
RUN mkdir -p ./apps/memory/config
COPY ./apps/memory/mix.exs ./apps/memory/

RUN mix do deps.get, deps.compile

# Add app code
COPY . .

# vim: set ft=dockerfile:
