---
version: "2"

services:

  app:
    build:
      context: ".."
      dockerfile: "./rel/Dockerfile.dev"
    command: "mix phoenix.server"
    ports:
      - "4000:4000"
    volumes:
      - "..:/opt/app"
    environment:
      - 'REDIS_URI="redis://redis:6379/0"'
    depends_on:
      - "redis"

  redis:
    image: redis
