FROM alpine:3.5

RUN apk --no-cache add ncurses-libs

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true

ADD progress.tar.gz /opt/app/

# Avoid running app as root
RUN adduser -S app-user
RUN chown -R app-user /opt/app/
USER app-user

ENTRYPOINT ["/opt/app/bin/progress"]

# vim: set ft=dockerfile:
